import assert from 'node:assert/strict';
import test from 'node:test';
import { createHash } from 'node:crypto';
import { Keypair, PublicKey } from '@solana/web3.js';
import {
  buildCommunityEventInstruction, buildInitializeCommunityInstruction, buildRotateCommunityAuthoritiesInstruction,
  buildWithdrawCommunityJourneyInstruction, COMMUNITY_CONFIG_SIZE, COMMUNITY_JOURNEY_SIZE, COMMUNITY_RECORD_SIZE,
  communityRecordMatchesEvent, decodeCommunityConfig, decodeCommunityJourney, decodeCommunityRecord,
  deriveCommunityRecordAddress, deriveCommunityWithdrawalAddress, fetchFinalizedCommunityJourney, reconstructCommunityProfile, type CommunityEventInput, type CommunityRecord,
} from '../src/community.ts';
const programId=Keypair.generate().publicKey,admin=Keypair.generate().publicKey,issuer=Keypair.generate().publicKey,sponsor=Keypair.generate().publicKey;
const journeyId='11'.repeat(32),rider='22'.repeat(32),guardian='33'.repeat(32);
function event(overrides:Partial<CommunityEventInput>={}):CommunityEventInput{return{journeyId,sequence:0,kind:'created',actorId:rider,subjectId:rider,assignment:0,observedAt:1234,value:0,...overrides};}
function record(overrides:Partial<CommunityRecord>={}):CommunityRecord{return{...event(),version:1,provenance:'platform-attested',ruleVersion:1,issuer,recordedAt:1240,points:0,reputation:0,targetSequence:0,...overrides};}
function bytes(name:string,size:number):Buffer{const b=Buffer.alloc(size);createHash('sha256').update(`account:${name}`).digest().copy(b,0,0,8);b[8]=1;return b;}
test('receipts bind journey, exact sequence, and program',()=>{const a=deriveCommunityRecordAddress(journeyId,0,programId);assert.ok(a.equals(deriveCommunityRecordAddress(journeyId,0,programId)));assert.ok(!a.equals(deriveCommunityRecordAddress(journeyId,1,programId)));assert.ok(!a.equals(deriveCommunityRecordAddress(journeyId,0,issuer)));});
test('append requires distinct issuer and sponsor signatures without member-wallet signature',()=>{const ix=buildCommunityEventInstruction({programId,issuer,sponsor,event:event()});assert.equal(ix.keys.filter(k=>k.isSigner).length,2);assert.ok(ix.keys[1].pubkey.equals(issuer));assert.ok(ix.keys[2].pubkey.equals(sponsor));assert.equal(ix.data.length,122);assert.throws(()=>buildCommunityEventInstruction({programId,issuer,sponsor:issuer,event:event()}));});
test('invalid identities, timestamps, unsigned fields, and unrecognized kinds are rejected before signing',()=>{for(const e of [event({journeyId:'0'.repeat(64)}),event({actorId:'AB'.repeat(32)}),event({sequence:-1}),event({assignment:2**32}),event({observedAt:Number.MAX_SAFE_INTEGER+1}),event({value:256}),event({kind:'withdrawn' as never})])assert.throws(()=>buildCommunityEventInstruction({programId,issuer,sponsor,event:e}));});
test('automatic relay request has no invented member actor',()=>{const e=event({kind:'relay_requested',actorId:'0'.repeat(64),subjectId:guardian,assignment:1,value:1});assert.doesNotThrow(()=>buildCommunityEventInstruction({programId,issuer,sponsor,event:e}));assert.throws(()=>buildCommunityEventInstruction({programId,issuer,sponsor,event:{...e,value:0}}));});
test('bootstrap binds the executable program and its upgradeable program-data account',()=>{const ix=buildInitializeCommunityInstruction({programId,admin,issuer,sponsor});assert.equal(ix.keys.length,5);assert.ok(ix.keys[2].pubkey.equals(programId));assert.throws(()=>buildInitializeCommunityInstruction({programId,admin,issuer:admin,sponsor}));const rotate=buildRotateCommunityAuthoritiesInstruction({programId,admin,nextAdmin:admin,nextIssuer:issuer,nextSponsor:sponsor,expectedRevision:3});assert.equal(rotate.data.readUInt32LE(104),3);});
test('withdrawal targets an older deterministic receipt and requires administrator plus sponsor',()=>{const ix=buildWithdrawCommunityJourneyInstruction({programId,admin,sponsor,journeyId,sequence:9,targetSequence:3,reason:1,observedAt:1240});assert.ok(ix.keys[4].pubkey.equals(deriveCommunityRecordAddress(journeyId,3,programId)));assert.equal(ix.keys.filter(k=>k.isSigner).length,2);assert.throws(()=>buildWithdrawCommunityJourneyInstruction({programId,admin,sponsor,journeyId,sequence:9,targetSequence:9,reason:1,observedAt:1240}));});
test('portable config and journey decoders match serialized offsets',()=>{const c=bytes('CommunityConfig',COMMUNITY_CONFIG_SIZE);admin.toBuffer().copy(c,9);issuer.toBuffer().copy(c,41);sponsor.toBuffer().copy(c,73);c.writeUInt32LE(2,105);assert.equal(decodeCommunityConfig(c).revision,2);const j=bytes('CommunityJourney',COMMUNITY_JOURNEY_SIZE);Buffer.from(journeyId,'hex').copy(j,9);j[123]=1;Buffer.from(guardian,'hex').copy(j,124);j.writeUInt32LE(2,156);j[160]=1;j.writeUInt32LE(3,162);const decoded=decodeCommunityJourney(j);assert.equal(decoded.journeyId,journeyId);assert.deepEqual(decoded.contributions,[{memberId:guardian,checkIns:2,claimed:true,thanked:false,lastAssignment:3}]);j[123]=17;assert.throws(()=>decodeCommunityJourney(j));});
test('receipt decoder preserves source, actor, claim amount, and correction target',()=>{const b=bytes('CommunityRecord',COMMUNITY_RECORD_SIZE);b[9]=1;b[10]=1;Buffer.from(journeyId,'hex').copy(b,11);b.writeUInt32LE(9,43);b[47]=6;Buffer.from(guardian,'hex').copy(b,48);Buffer.from(guardian,'hex').copy(b,80);b.writeUInt32LE(3,112);b.writeBigInt64LE(1234n,116);issuer.toBuffer().copy(b,125);b.writeBigInt64LE(1240n,157);b.writeUInt16LE(13,165);b.writeUInt16LE(5,167);const decoded=decodeCommunityRecord(b);assert.equal(decoded.points,13);assert.equal(decoded.reputation,5);assert.equal(decoded.provenance,'platform-attested');assert.ok(communityRecordMatchesEvent(decoded,event({sequence:9,kind:'contribution',actorId:guardian,subjectId:guardian,assignment:3})));b[9]=2;assert.throws(()=>decodeCommunityRecord(b));});
test('profile reconstruction deduplicates receipts, never awards points for banners, and honors withdrawal',()=>{const contribution=record({sequence:5,kind:'contribution',subjectId:guardian,actorId:guardian,points:25,reputation:10});const thanks=record({sequence:6,kind:'gratitude',subjectId:guardian,value:2});const profile=reconstructCommunityProfile(guardian,[contribution,contribution,thanks]);assert.equal(profile.points,25);assert.equal(profile.completedGuards,1);assert.equal(profile.gratitude.thoughtfulness,1);const withdrawn=record({sequence:7,kind:'withdrawn',value:1,targetSequence:5});const corrected=reconstructCommunityProfile(guardian,[contribution,thanks,withdrawn]);assert.equal(corrected.points,0);assert.equal(corrected.gratitude.total,0);assert.deepEqual(corrected.withdrawnJourneys,[journeyId]);});
test('conflicting receipts and multiple contributions for one journey fail reconstruction',()=>{const c=record({sequence:5,kind:'contribution',subjectId:guardian,actorId:guardian,points:25,reputation:10});assert.throws(()=>reconstructCommunityProfile(guardian,[c,{...c,points:99}]));assert.throws(()=>reconstructCommunityProfile(guardian,[c,{...c,sequence:6}]));});
test('late source receipt and administrative withdrawal may share a sequence snapshot without colliding',()=>{const c=record({sequence:5,kind:'contribution',subjectId:guardian,actorId:guardian,points:25,reputation:10});const w=record({sequence:5,kind:'withdrawn',value:1,targetSequence:4});assert.equal(reconstructCommunityProfile(guardian,[c,w]).points,0);assert.ok(!deriveCommunityWithdrawalAddress(journeyId,programId).equals(deriveCommunityRecordAddress(journeyId,5,programId)));});
test('independent finalized retrieval rejects foreign owners before trusting records',async()=>{const connection={getAccountInfoAndContext:async()=>({context:{slot:123},value:{owner:issuer,executable:false,data:Buffer.alloc(0)}})};await assert.rejects(fetchFinalizedCommunityJourney(connection as never,programId,journeyId),/different program/);});
test('independent finalized retrieval includes the separate withdrawal account and validates its linkage',async()=>{
  const j=bytes('CommunityJourney',COMMUNITY_JOURNEY_SIZE);Buffer.from(journeyId,'hex').copy(j,9);j.writeUInt32LE(1,73);j[113]=2;j[114]=1;
  const created=bytes('CommunityRecord',COMMUNITY_RECORD_SIZE);created[9]=1;created[10]=1;Buffer.from(journeyId,'hex').copy(created,11);created[47]=1;
  const withdrawn=Buffer.from(created);withdrawn[47]=8;withdrawn.writeUInt32LE(1,43);withdrawn[124]=1;
  const account=(data:Buffer)=>({owner:programId,executable:false,data});
  const connection={getAccountInfoAndContext:async()=>({context:{slot:123},value:account(j)}),getMultipleAccountsInfo:async()=>[account(created)],getAccountInfo:async(address:PublicKey)=>{assert.ok(address.equals(deriveCommunityWithdrawalAddress(journeyId,programId)));return account(withdrawn);}};
  const proof=await fetchFinalizedCommunityJourney(connection as never,programId,journeyId);assert.equal(proof.records.length,2);assert.equal(proof.asOfSlot,123);assert.equal(proof.records[1].kind,'withdrawn');
  withdrawn.writeUInt32LE(1,169);await assert.rejects(fetchFinalizedCommunityJourney(connection as never,programId,journeyId),/Invalid withdrawal/);
});
